// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: grpc/proto/tabelogoSpider.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TabelogoSpiderService_GetTabelogInfo_FullMethodName  = "/grpctabelogo.TabelogoSpiderService/GetTabelogInfo"
	TabelogoSpiderService_GetTabelogPhoto_FullMethodName = "/grpctabelogo.TabelogoSpiderService/GetTabelogPhoto"
)

// TabelogoSpiderServiceClient is the client API for TabelogoSpiderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TabelogoSpiderServiceClient interface {
	GetTabelogInfo(ctx context.Context, in *GetTabelogInfoRequest, opts ...grpc.CallOption) (*TabelogInfoResponseList, error)
	GetTabelogPhoto(ctx context.Context, in *GetTabelogPhotoRequest, opts ...grpc.CallOption) (*TabelogPhotoResponse, error)
}

type tabelogoSpiderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTabelogoSpiderServiceClient(cc grpc.ClientConnInterface) TabelogoSpiderServiceClient {
	return &tabelogoSpiderServiceClient{cc}
}

func (c *tabelogoSpiderServiceClient) GetTabelogInfo(ctx context.Context, in *GetTabelogInfoRequest, opts ...grpc.CallOption) (*TabelogInfoResponseList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TabelogInfoResponseList)
	err := c.cc.Invoke(ctx, TabelogoSpiderService_GetTabelogInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabelogoSpiderServiceClient) GetTabelogPhoto(ctx context.Context, in *GetTabelogPhotoRequest, opts ...grpc.CallOption) (*TabelogPhotoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TabelogPhotoResponse)
	err := c.cc.Invoke(ctx, TabelogoSpiderService_GetTabelogPhoto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TabelogoSpiderServiceServer is the server API for TabelogoSpiderService service.
// All implementations must embed UnimplementedTabelogoSpiderServiceServer
// for forward compatibility.
type TabelogoSpiderServiceServer interface {
	GetTabelogInfo(context.Context, *GetTabelogInfoRequest) (*TabelogInfoResponseList, error)
	GetTabelogPhoto(context.Context, *GetTabelogPhotoRequest) (*TabelogPhotoResponse, error)
	mustEmbedUnimplementedTabelogoSpiderServiceServer()
}

// UnimplementedTabelogoSpiderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTabelogoSpiderServiceServer struct{}

func (UnimplementedTabelogoSpiderServiceServer) GetTabelogInfo(context.Context, *GetTabelogInfoRequest) (*TabelogInfoResponseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTabelogInfo not implemented")
}
func (UnimplementedTabelogoSpiderServiceServer) GetTabelogPhoto(context.Context, *GetTabelogPhotoRequest) (*TabelogPhotoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTabelogPhoto not implemented")
}
func (UnimplementedTabelogoSpiderServiceServer) mustEmbedUnimplementedTabelogoSpiderServiceServer() {}
func (UnimplementedTabelogoSpiderServiceServer) testEmbeddedByValue()                               {}

// UnsafeTabelogoSpiderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TabelogoSpiderServiceServer will
// result in compilation errors.
type UnsafeTabelogoSpiderServiceServer interface {
	mustEmbedUnimplementedTabelogoSpiderServiceServer()
}

func RegisterTabelogoSpiderServiceServer(s grpc.ServiceRegistrar, srv TabelogoSpiderServiceServer) {
	// If the following call pancis, it indicates UnimplementedTabelogoSpiderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TabelogoSpiderService_ServiceDesc, srv)
}

func _TabelogoSpiderService_GetTabelogInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTabelogInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabelogoSpiderServiceServer).GetTabelogInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabelogoSpiderService_GetTabelogInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabelogoSpiderServiceServer).GetTabelogInfo(ctx, req.(*GetTabelogInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TabelogoSpiderService_GetTabelogPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTabelogPhotoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabelogoSpiderServiceServer).GetTabelogPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TabelogoSpiderService_GetTabelogPhoto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabelogoSpiderServiceServer).GetTabelogPhoto(ctx, req.(*GetTabelogPhotoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TabelogoSpiderService_ServiceDesc is the grpc.ServiceDesc for TabelogoSpiderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TabelogoSpiderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpctabelogo.TabelogoSpiderService",
	HandlerType: (*TabelogoSpiderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTabelogInfo",
			Handler:    _TabelogoSpiderService_GetTabelogInfo_Handler,
		},
		{
			MethodName: "GetTabelogPhoto",
			Handler:    _TabelogoSpiderService_GetTabelogPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/tabelogoSpider.proto",
}
