// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.2
// source: grpc/proto/tabelogoSpider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTabelogInfoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Area            string                 `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	PlaceName       string                 `protobuf:"bytes,2,opt,name=place_name,json=placeName,proto3" json:"place_name,omitempty"`
	MaxResultAmount int32                  `protobuf:"varint,3,opt,name=max_result_amount,json=maxResultAmount,proto3" json:"max_result_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTabelogInfoRequest) Reset() {
	*x = GetTabelogInfoRequest{}
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTabelogInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTabelogInfoRequest) ProtoMessage() {}

func (x *GetTabelogInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTabelogInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTabelogInfoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_tabelogoSpider_proto_rawDescGZIP(), []int{0}
}

func (x *GetTabelogInfoRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *GetTabelogInfoRequest) GetPlaceName() string {
	if x != nil {
		return x.PlaceName
	}
	return ""
}

func (x *GetTabelogInfoRequest) GetMaxResultAmount() int32 {
	if x != nil {
		return x.MaxResultAmount
	}
	return 0
}

type TabelogInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating        string                 `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	RatingCount   string                 `protobuf:"bytes,4,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	Bookmarks     string                 `protobuf:"bytes,5,opt,name=bookmarks,proto3" json:"bookmarks,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Type          []string               `protobuf:"bytes,7,rep,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabelogInfoResponse) Reset() {
	*x = TabelogInfoResponse{}
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabelogInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabelogInfoResponse) ProtoMessage() {}

func (x *TabelogInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabelogInfoResponse.ProtoReflect.Descriptor instead.
func (*TabelogInfoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_tabelogoSpider_proto_rawDescGZIP(), []int{1}
}

func (x *TabelogInfoResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *TabelogInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TabelogInfoResponse) GetRating() string {
	if x != nil {
		return x.Rating
	}
	return ""
}

func (x *TabelogInfoResponse) GetRatingCount() string {
	if x != nil {
		return x.RatingCount
	}
	return ""
}

func (x *TabelogInfoResponse) GetBookmarks() string {
	if x != nil {
		return x.Bookmarks
	}
	return ""
}

func (x *TabelogInfoResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *TabelogInfoResponse) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

type TabelogInfoResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TabelogInfos  []*TabelogInfoResponse `protobuf:"bytes,1,rep,name=tabelog_infos,json=tabelogInfos,proto3" json:"tabelog_infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabelogInfoResponseList) Reset() {
	*x = TabelogInfoResponseList{}
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabelogInfoResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabelogInfoResponseList) ProtoMessage() {}

func (x *TabelogInfoResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabelogInfoResponseList.ProtoReflect.Descriptor instead.
func (*TabelogInfoResponseList) Descriptor() ([]byte, []int) {
	return file_grpc_proto_tabelogoSpider_proto_rawDescGZIP(), []int{2}
}

func (x *TabelogInfoResponseList) GetTabelogInfos() []*TabelogInfoResponse {
	if x != nil {
		return x.TabelogInfos
	}
	return nil
}

type GetTabelogPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTabelogPhotoRequest) Reset() {
	*x = GetTabelogPhotoRequest{}
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTabelogPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTabelogPhotoRequest) ProtoMessage() {}

func (x *GetTabelogPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTabelogPhotoRequest.ProtoReflect.Descriptor instead.
func (*GetTabelogPhotoRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_tabelogoSpider_proto_rawDescGZIP(), []int{3}
}

func (x *GetTabelogPhotoRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type TabelogPhotoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Photo         []string               `protobuf:"bytes,2,rep,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TabelogPhotoResponse) Reset() {
	*x = TabelogPhotoResponse{}
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TabelogPhotoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TabelogPhotoResponse) ProtoMessage() {}

func (x *TabelogPhotoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_tabelogoSpider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TabelogPhotoResponse.ProtoReflect.Descriptor instead.
func (*TabelogPhotoResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_tabelogoSpider_proto_rawDescGZIP(), []int{4}
}

func (x *TabelogPhotoResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *TabelogPhotoResponse) GetPhoto() []string {
	if x != nil {
		return x.Photo
	}
	return nil
}

var File_grpc_proto_tabelogoSpider_proto protoreflect.FileDescriptor

var file_grpc_proto_tabelogoSpider_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x61, 0x62,
	0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x22,
	0x76, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x6d,
	0x61, 0x78, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x6d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xc0, 0x01, 0x0a, 0x13, 0x54, 0x61, 0x62, 0x65,
	0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x6d, 0x61, 0x72, 0x6b, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x61, 0x0a, 0x17, 0x54, 0x61,
	0x62, 0x65, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x0d, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x2e, 0x54, 0x61, 0x62, 0x65,
	0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0c, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x2c, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x50, 0x68, 0x6f, 0x74, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x40, 0x0a, 0x14, 0x54,
	0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x32, 0xd2, 0x01,
	0x0a, 0x15, 0x54, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x62, 0x65, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x65,
	0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x2e, 0x54, 0x61,
	0x62, 0x65, 0x6c, 0x6f, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x5b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x65,
	0x6c, 0x6f, 0x67, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x24, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x74,
	0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x65, 0x6c,
	0x6f, 0x67, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x2e, 0x54, 0x61,
	0x62, 0x65, 0x6c, 0x6f, 0x67, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x74, 0x61, 0x62, 0x65, 0x6c, 0x6f, 0x67, 0x2d, 0x73, 0x70,
	0x69, 0x64, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_proto_tabelogoSpider_proto_rawDescOnce sync.Once
	file_grpc_proto_tabelogoSpider_proto_rawDescData = file_grpc_proto_tabelogoSpider_proto_rawDesc
)

func file_grpc_proto_tabelogoSpider_proto_rawDescGZIP() []byte {
	file_grpc_proto_tabelogoSpider_proto_rawDescOnce.Do(func() {
		file_grpc_proto_tabelogoSpider_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_proto_tabelogoSpider_proto_rawDescData)
	})
	return file_grpc_proto_tabelogoSpider_proto_rawDescData
}

var file_grpc_proto_tabelogoSpider_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_proto_tabelogoSpider_proto_goTypes = []any{
	(*GetTabelogInfoRequest)(nil),   // 0: grpctabelogo.GetTabelogInfoRequest
	(*TabelogInfoResponse)(nil),     // 1: grpctabelogo.TabelogInfoResponse
	(*TabelogInfoResponseList)(nil), // 2: grpctabelogo.TabelogInfoResponseList
	(*GetTabelogPhotoRequest)(nil),  // 3: grpctabelogo.GetTabelogPhotoRequest
	(*TabelogPhotoResponse)(nil),    // 4: grpctabelogo.TabelogPhotoResponse
}
var file_grpc_proto_tabelogoSpider_proto_depIdxs = []int32{
	1, // 0: grpctabelogo.TabelogInfoResponseList.tabelog_infos:type_name -> grpctabelogo.TabelogInfoResponse
	0, // 1: grpctabelogo.TabelogoSpiderService.GetTabelogInfo:input_type -> grpctabelogo.GetTabelogInfoRequest
	3, // 2: grpctabelogo.TabelogoSpiderService.GetTabelogPhoto:input_type -> grpctabelogo.GetTabelogPhotoRequest
	2, // 3: grpctabelogo.TabelogoSpiderService.GetTabelogInfo:output_type -> grpctabelogo.TabelogInfoResponseList
	4, // 4: grpctabelogo.TabelogoSpiderService.GetTabelogPhoto:output_type -> grpctabelogo.TabelogPhotoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_proto_tabelogoSpider_proto_init() }
func file_grpc_proto_tabelogoSpider_proto_init() {
	if File_grpc_proto_tabelogoSpider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_proto_tabelogoSpider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_tabelogoSpider_proto_goTypes,
		DependencyIndexes: file_grpc_proto_tabelogoSpider_proto_depIdxs,
		MessageInfos:      file_grpc_proto_tabelogoSpider_proto_msgTypes,
	}.Build()
	File_grpc_proto_tabelogoSpider_proto = out.File
	file_grpc_proto_tabelogoSpider_proto_rawDesc = nil
	file_grpc_proto_tabelogoSpider_proto_goTypes = nil
	file_grpc_proto_tabelogoSpider_proto_depIdxs = nil
}
