// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"authenticate/config"
	"github.com/redis/go-redis/v9"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitControllerHandle(db *gorm.DB, config2 *config.Config, logger *zap.Logger, redisClient *redis.Client, symmetricKey string) *ControllerHandle {
	userWithTransactionHandler := provideUserWithTransactionRepository(db)
	registUserServiceHandler := provideRegistUserService(userWithTransactionHandler)
	registUserControllerHandle := provideRegistUserController(registUserServiceHandler)
	userAndSessionWithTransactionHandler := provideUserAndSessionWithTransactionRepository(db)
	maker := provideTokenMaker(symmetricKey)
	sessionWithTransactionHandler := provideSessionWithTransactionRedisRepository(redisClient)
	loginUserServiceHandler := provideLoginUserService(userAndSessionWithTransactionHandler, maker, sessionWithTransactionHandler, config2)
	loginUserControllerHandle := provideLoginUserController(loginUserServiceHandler)
	renewAccessTokenServiceHandler := provideRenewAccessTokenService(userAndSessionWithTransactionHandler, maker, sessionWithTransactionHandler, config2)
	renewAccessTokenControllerHandle := provideRenewAccessTokenController(renewAccessTokenServiceHandler)
	userAndPlaceAndFavoriteWithTransactionHandler := provideUserAndPlaceAndFavoriteWithTransactionRepository(db)
	placeWithTransactionHandler := providePlaceWithTransactionRedisRepository(redisClient)
	saveFavoriteServiceHandler := provideSaveFavoriteService(userAndPlaceAndFavoriteWithTransactionHandler, placeWithTransactionHandler, config2)
	saveFavoriteControllerHandle := provideSaveFavoriteController(saveFavoriteServiceHandler)
	favoriteHandler := provideFavoriteRepository(db)
	getUserFavoritesServiceHandler := provideGetUserFavoritesService(favoriteHandler)
	getUserFavoritesControllerHandle := provideGetUserFavoritesController(getUserFavoritesServiceHandler)
	repositoryPlaceWithTransactionHandler := providePlaceWithTransactionRepository(db)
	savePlaceServiceHandler := provideSavePlaceService(repositoryPlaceWithTransactionHandler)
	savePlaceControllerHandle := provideSavePlaceController(savePlaceServiceHandler)
	placeHandler := providePlaceRepository(db)
	redisDBPlaceHandler := providePlaceRedisRepository(redisClient)
	getPlaceServiceHandler := provideGetPlaceService(placeHandler, redisDBPlaceHandler)
	getPlaceControllerHandle := provideGetPlaceController(getPlaceServiceHandler)
	logoutUserServiceHandler := provideLogoutUserService(userAndSessionWithTransactionHandler, sessionWithTransactionHandler)
	logoutUserControllerHandle := provideLogoutUserController(logoutUserServiceHandler)
	userServiceServer := provideUserServiceServer(registUserServiceHandler, loginUserServiceHandler, renewAccessTokenServiceHandler, logoutUserServiceHandler, saveFavoriteServiceHandler, getUserFavoritesServiceHandler)
	placeServiceServer := providePlaceServiceServer(savePlaceServiceHandler, getPlaceServiceHandler)
	controllerHandle := newControllerHandle(registUserControllerHandle, loginUserControllerHandle, renewAccessTokenControllerHandle, saveFavoriteControllerHandle, getUserFavoritesControllerHandle, savePlaceControllerHandle, getPlaceControllerHandle, logoutUserControllerHandle, userServiceServer, placeServiceServer)
	return controllerHandle
}
