// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Favorite struct {
	FavoriteID int64     `json:"favorite_id"`
	IsFavorite bool      `json:"is_favorite"`
	UserID     int64     `json:"user_id"`
	GoogleID   string    `json:"google_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Place struct {
	GoogleID                 string    `json:"google_id"`
	TwDisplayName            string    `json:"tw_display_name"`
	TwFormattedAddress       string    `json:"tw_formatted_address"`
	TwWeekdayDescriptions    []string  `json:"tw_weekday_descriptions"`
	AdministrativeAreaLevel1 string    `json:"administrative_area_level_1"`
	Country                  string    `json:"country"`
	GoogleMapUri             string    `json:"google_map_uri"`
	InternationalPhoneNumber string    `json:"international_phone_number"`
	Lat                      string    `json:"lat"`
	Lng                      string    `json:"lng"`
	PrimaryType              string    `json:"primary_type"`
	Rating                   string    `json:"rating"`
	Types                    []string  `json:"types"`
	UserRatingCount          int32     `json:"user_rating_count"`
	WebsiteUri               string    `json:"website_uri"`
	PlaceVersion             int32     `json:"place_version"`
	CreatedAt                time.Time `json:"created_at"`
	UpdatedAt                time.Time `json:"updated_at"`
}

type Session struct {
	SessionID    uuid.UUID `json:"session_id"`
	Email        string    `json:"email"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	UserID         int64     `json:"user_id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Active         bool      `json:"active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
