// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"


	"github.com/google/uuid"
)

type Querier interface {
	CreateFavorite(ctx context.Context, arg CreateFavoriteParams) (Favorite, error)
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (Place, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePlace(ctx context.Context, arg DeletePlaceParams) error
	GetCountryList(ctx context.Context, userEmail string) ([]string, error)
	GetFavorite(ctx context.Context, arg GetFavoriteParams) (Favorite, error)
	GetPlaceByGoogleId(ctx context.Context, googleID string) (Place, error)
	GetRegionList(ctx context.Context, arg GetRegionListParams) ([]string, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListFavoritesByCountrAndRegion(ctx context.Context, arg ListFavoritesByCountrAndRegionParams) ([]ListFavoritesByCountrAndRegionRow, error)
	ListFavoritesByCountry(ctx context.Context, arg ListFavoritesByCountryParams) ([]ListFavoritesByCountryRow, error)
	ListFavoritesByCreateTime(ctx context.Context, arg ListFavoritesByCreateTimeParams) ([]ListFavoritesByCreateTimeRow, error)
	RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error
	ToggleFavorite(ctx context.Context, arg ToggleFavoriteParams) (Favorite, error)
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (Place, error)
}

var _ Querier = (*Queries)(nil)
