// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: grpc/proto/googleMap.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoogleMapService_QuickSearch_FullMethodName   = "/grpcgooglemap.GoogleMapService/QuickSearch"
	GoogleMapService_AdvanceSearch_FullMethodName = "/grpcgooglemap.GoogleMapService/AdvanceSearch"
)

// GoogleMapServiceClient is the client API for GoogleMapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoogleMapServiceClient interface {
	QuickSearch(ctx context.Context, in *QuickSearchRequest, opts ...grpc.CallOption) (*InterfaceResponse, error)
	AdvanceSearch(ctx context.Context, in *AdvanceSearchRequest, opts ...grpc.CallOption) (*InterfaceResponse, error)
}

type googleMapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoogleMapServiceClient(cc grpc.ClientConnInterface) GoogleMapServiceClient {
	return &googleMapServiceClient{cc}
}

func (c *googleMapServiceClient) QuickSearch(ctx context.Context, in *QuickSearchRequest, opts ...grpc.CallOption) (*InterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfaceResponse)
	err := c.cc.Invoke(ctx, GoogleMapService_QuickSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *googleMapServiceClient) AdvanceSearch(ctx context.Context, in *AdvanceSearchRequest, opts ...grpc.CallOption) (*InterfaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterfaceResponse)
	err := c.cc.Invoke(ctx, GoogleMapService_AdvanceSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoogleMapServiceServer is the server API for GoogleMapService service.
// All implementations must embed UnimplementedGoogleMapServiceServer
// for forward compatibility.
type GoogleMapServiceServer interface {
	QuickSearch(context.Context, *QuickSearchRequest) (*InterfaceResponse, error)
	AdvanceSearch(context.Context, *AdvanceSearchRequest) (*InterfaceResponse, error)
	mustEmbedUnimplementedGoogleMapServiceServer()
}

// UnimplementedGoogleMapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoogleMapServiceServer struct{}

func (UnimplementedGoogleMapServiceServer) QuickSearch(context.Context, *QuickSearchRequest) (*InterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuickSearch not implemented")
}
func (UnimplementedGoogleMapServiceServer) AdvanceSearch(context.Context, *AdvanceSearchRequest) (*InterfaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdvanceSearch not implemented")
}
func (UnimplementedGoogleMapServiceServer) mustEmbedUnimplementedGoogleMapServiceServer() {}
func (UnimplementedGoogleMapServiceServer) testEmbeddedByValue()                          {}

// UnsafeGoogleMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoogleMapServiceServer will
// result in compilation errors.
type UnsafeGoogleMapServiceServer interface {
	mustEmbedUnimplementedGoogleMapServiceServer()
}

func RegisterGoogleMapServiceServer(s grpc.ServiceRegistrar, srv GoogleMapServiceServer) {
	// If the following call pancis, it indicates UnimplementedGoogleMapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoogleMapService_ServiceDesc, srv)
}

func _GoogleMapService_QuickSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuickSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleMapServiceServer).QuickSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleMapService_QuickSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleMapServiceServer).QuickSearch(ctx, req.(*QuickSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoogleMapService_AdvanceSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvanceSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoogleMapServiceServer).AdvanceSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoogleMapService_AdvanceSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoogleMapServiceServer).AdvanceSearch(ctx, req.(*AdvanceSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoogleMapService_ServiceDesc is the grpc.ServiceDesc for GoogleMapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoogleMapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcgooglemap.GoogleMapService",
	HandlerType: (*GoogleMapServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuickSearch",
			Handler:    _GoogleMapService_QuickSearch_Handler,
		},
		{
			MethodName: "AdvanceSearch",
			Handler:    _GoogleMapService_AdvanceSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/googleMap.proto",
}
