apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticate-service
  template:
    metadata:
      labels:
        app: authenticate-service
    spec:
      containers:
      - name: authenticate-service
        image: "leon180/tabelogo-authenticate-service:1.0.1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: authenticate-service
spec:
  selector:
    app: authenticate-service
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
