// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "your-email@domain.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/getTabelogInfo": {
            "get": {
                "description": "タブログ情報取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabelogo-spider"
                ],
                "summary": "タブログ情報取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "エリア",
                        "name": "area",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "店名",
                        "name": "place_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大取得件数",
                        "name": "max_result_amount",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responsemodel.TabelogInfoResponseList"
                        }
                    }
                }
            }
        },
        "/getTabelogPhoto": {
            "get": {
                "description": "タブログ写真取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tabelogo-spider"
                ],
                "summary": "タブログ写真取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "リンク",
                        "name": "link",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responsemodel.TabelogPhotoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "enum.URL": {
            "type": "string",
            "enum": [
                "https://tabelog.com/"
            ],
            "x-enum-varnames": [
                "TabelogBaseURL"
            ]
        },
        "responsemodel.TabelogInfoResponse": {
            "type": "object",
            "properties": {
                "bookmarks": {
                    "type": "string"
                },
                "link": {
                    "$ref": "#/definitions/enum.URL"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "rating": {
                    "type": "string"
                },
                "ratingCount": {
                    "type": "string"
                },
                "type": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "responsemodel.TabelogInfoResponseList": {
            "type": "object",
            "properties": {
                "tabelog_infos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responsemodel.TabelogInfoResponse"
                    }
                }
            }
        },
        "responsemodel.TabelogPhotoResponse": {
            "type": "object",
            "properties": {
                "link": {
                    "$ref": "#/definitions/enum.URL"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/tabelogo-spider",
	Schemes:          []string{},
	Title:            "Tabelog Spider API",
	Description:      "Tabelog Spider service API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
