// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"go.mongodb.org/mongo-driver/mongo"
	"go.uber.org/zap"
	"logger-service/config"
)

// Injectors from wire.go:

func InitControllerHandle(config2 config.Config, logger *zap.Logger, db *mongo.Client) *ControllerHandle {
	createLogHandler := provideCreateLogRepository(db)
	serviceCreateLogHandler := provideCreateLogService(createLogHandler)
	readLogHandler := provideReadLogRepository(db)
	serviceReadLogHandler := provideReadLogService(readLogHandler)
	updateLogHandler := provideUpdateLogRepository(db)
	serviceUpdateLogHandler := provideUpdateLogService(updateLogHandler)
	deleteLogHandler := provideDeleteLogRepository(db)
	serviceDeleteLogHandler := provideDeleteLogService(deleteLogHandler)
	logController := provideLogController(serviceCreateLogHandler, serviceReadLogHandler, serviceUpdateLogHandler, serviceDeleteLogHandler)
	logServiceServer := provideLogServiceServer(serviceCreateLogHandler, serviceReadLogHandler, serviceUpdateLogHandler, serviceDeleteLogHandler)
	controllerHandle := newControllerHandle(logController, logServiceServer)
	return controllerHandle
}
