// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"go.uber.org/zap"
	"google-map/config"
)

// Injectors from wire.go:

func InitControllerHandle(config2 *config.Config, logger *zap.Logger) *ControllerHandle {
	googlePlaceSearchHandler := provideSearchService(config2)
	googlePlaceSearchHandle := provideSearchController(googlePlaceSearchHandler, config2)
	googleMapServiceServer := provideGoogleMapServiceServer(googlePlaceSearchHandler, config2)
	controllerHandle := newControllerHandle(googlePlaceSearchHandle, googleMapServiceServer)
	return controllerHandle
}
