// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitControllerHandle(logger *zap.Logger) *ControllerHandle {
	getTabelogInfoHandler := provideGetTabelogInfoService()
	getTabelogPhotoHandler := provideGetTabelogPhotoService()
	getTabelogInfoHandle := provideGetTabelogInfoController(getTabelogInfoHandler, getTabelogPhotoHandler)
	controllerHandle := newControllerHandle(getTabelogInfoHandle)
	return controllerHandle
}
