// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "your-email@domain.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/advanceSearch": {
            "get": {
                "description": "詳細検索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-map-search"
                ],
                "summary": "詳細検索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "テキストクエリ",
                        "name": "text_query",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "低緯度",
                        "name": "low_latitude",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "低経度",
                        "name": "low_longitude",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "高緯度",
                        "name": "high_latitude",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "高経度",
                        "name": "high_longitude",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大取得件数",
                        "name": "max_result_count",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最低評価",
                        "name": "min_rating",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "現在開いているか",
                        "name": "open_now",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ランク優先度",
                        "name": "rank_preference",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "言語",
                        "name": "language_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "APIマスク",
                        "name": "api_mask",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responsemodel.CommonResponse"
                        }
                    }
                }
            }
        },
        "/quickSearch": {
            "get": {
                "description": "クイック検索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-map-search"
                ],
                "summary": "クイック検索",
                "parameters": [
                    {
                        "type": "string",
                        "description": "キーワード",
                        "name": "place_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "APIマスク",
                        "name": "api_mask",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "言語",
                        "name": "language_code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/responsemodel.CommonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responsemodel.CommonResponse": {
            "type": "object",
            "properties": {
                "result": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:80",
	BasePath:         "/google-map-search",
	Schemes:          []string{},
	Title:            "Google Map API",
	Description:      "Google Map service API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
